$(".pre_header_info").remove();
$(".header_dropdowns").remove();
$(".header_nav").remove();
$(".search_product_right").remove();
$(".banners_widget").remove();
$(".ri_dropdown").remove();
$(".header_logo").html('<img src="/img/logo.svg" alt="" title="">');
$("footer").remove();
$('a[href$="/projects/dashboard/"]').remove();
$('a[href$="/checklist/index/"]').remove();
$('a[href$="/backlink/competitors/"]').remove();
$('a[href$="/projects/"]').remove();
$("span:contains('Site Audit')").remove();
$("span:contains('Rank Tracker')").remove();
$("span:contains('Hide menu')").parent().remove();
$('body').mouseover(function () {
    $(".pre_header_info").remove();
    $(".banners_widget").remove();
    $(".header_dropdowns").remove();
    $(".header_nav").remove();
    $(".search_product_right").remove();
    $(".ri_dropdown").remove();
    $(".header_logo").html('<img src="/img/logo.svg" alt="" title="">');
    $("footer").remove();
    $('a[href$="/projects/dashboard/"]').remove();
    $('a[href$="/projects/"]').remove();
    $('a[href$="/checklist/index/"]').remove();
    $('a[href$="/backlink/competitors/"]').remove();
    $("span:contains('Site Audit')").remove();
    $("span:contains('Rank Tracker')").remove();
    $("span:contains('Hide menu')").parent().remove();
});
